version: '2.1'
services:
  ezweb:
    build: ./easyweb
    image: docimg/ctf-2020-dycb-easyweb
    ports:
      - "6666:80"
    restart: always
    container_name: easyweb
    sysctls:
      - net.ipv4.ip_forward=0
      - net.ipv4.conf.all.forwarding = 0
      - net.ipv6.conf.all.forwarding=0
      - net.ipv6.conf.all.disable_ipv6=1
